CREATE TABLE STUDENT(REGNO VARCHAR(30) PRIMARY KEY,NAME VARCHAR(30) NOT NULL,MAJOR VARCHAR(30) NOT NULL,BDATE DATE NOT NULL);CREATE TABLE COURSE(COURSE INTEGER PRIMARY KEY,CNAME VARCHAR(30) NOT NULL,DEPT VARCHAR(30) NOT NULL);CREATE TABLE ENROLL(REG_NO VARCHAR(30) NOT NULL,COURSE INTEGER NOT NULL,SEM INTEGER NOT NULL,MARKS INTEGER NOT NULL,PRIMARY KEY(REG_NO,COURSE_,SEM),FOREIGN KEY (REG_NO) REFERENCES STUDENT(REGNO) DELETE ONCASCADE,FOREIGN KEY (COURSE) REFERENCES COURSE(COURSE) DELETE ONCASCADE);CREATE TABLE TEXT(BOOKISBN INTEGER PRIMARY KEY,BOOKTITLE VARCHAR(30) NOT NULL,PUBLISHER VARCHAR(30) NOT NULL,AUTHOR VARCHAR(30) NOT NULL);CREATE TABLE BOOK_ADOPTION(COURSE INTEGER NOT NULL,SEM INTEGER NOT NULL,
24


BOOK_ISBN INTEGER NOT NULL,PRIMARY KEY(COURSE_,SEM,BOOK_ISBN),FOREIGN KEY (COURSE) REFERENCES COURSE(COURSE) DELETE ONCASCADE,FOREIGN KEY(BOOK_ISBN) REFERENCES TEXT(BOOKISBN) DELETE ONCASCADE);INSERT INTO STUDENT VALUES('1BM02IS012','ANSHUMANATRI','DATBASE','15-JAN-84');INSERT INTO STUDENT VALUES('1BM02CS012','A MNC','DMS','25-FEB-84');INSERT INTO STUDENT VALUES('1BM02TC012','TELE TECHNO','SSDT','11-DEC-84');INSERT INTO STUDENT VALUES('1BM02EE012','ELCTRA','POWER GENERATION','1-APR-84');INSERT INTO STUDENT VALUES('1BM02EC012','GG','POWER ELECTRONICS','5-NOV-84');INSERT INTO COURSE VALUES(1,'DATABASE','IS');INSERT INTO COURSE VALUES(2,'DMS','IS');INSERT INTO COURSE VALUES(3,'SSDT','TC');INSERT INTO COURSE VALUES(4,'POWER GENERATION','EE');INSERT INTO COURSE VALUES(5,'POWER ELECTRONICS','EC');INSERT INTO TEXT VALUES(1,'DATABASE A SYSTEMATICAPPROACH','JOHN WILEY','R ASHOK KUMAR');INSERT INTO TEXT VALUES(2,'DMS FOR DUMMIES','PEARSON','MADHUPRIYA');INSERT INTO TEXT VALUES(3,'SSDT NO ONE CAN TEACHBETTER','PEARSON','GAURA');INSERT INTO TEXT VALUES(4,'POWER GENERATIONBIBLE','TMH','MEENA');INSERT INTO TEXT VALUES(5,'POWER OF POWER ELECTRONICS','OREILLY','GG THE GREAT');INSERT INTO ENROLL VALUES('1BM02IS012',1,5,98);INSERT INTO ENROLL VALUES('1BM02CS012',2,3,88);INSERT INTO ENROLL VALUES('1BM02TC012',3,5,88);INSERT INTO ENROLL VALUES('1BM02EE012',4,5,88);INSERT INTO ENROLL VALUES('1BM02EC012',5,5,88);
25

INSERT INTO BOOK_ADOPTION VALUES(1,5,1);INSERT INTO BOOK_ADOPTION VALUES(2,3,2);INSERT INTO BOOK_ADOPTION VALUES(3,5,3);INSERT INTO BOOK_ADOPTION VALUES(4,5,4);INSERT INTO BOOK_ADOPTION VALUES(5,5,5);







CREATE TABLE STUDENT(REGNO VARCHAR(30) PRIMARY KEY,NAME VARCHAR(30) NOT NULL,MAJOR VARCHAR(30) NOT NULL,BDATE DATE NOT NULL);

CREATE TABLE COURSE(COURSE INTEGER PRIMARY KEY,CNAME VARCHAR(30) NOT NULL,DEPT VARCHAR(30) NOT NULL);

CREATE TABLE ENROLL(REG_NO VARCHAR(30) NOT NULL,COURSE INTEGER NOT NULL,SEM INTEGER NOT NULL,MARKS INTEGER NOT NULL,PRIMARY KEY(REG_NO,COURSE_,SEM));


CREATE TABLE TEXT(BOOKISBN INTEGER PRIMARY KEY,BOOKTITLE VARCHAR(30) NOT NULL,PUBLISHER VARCHAR(30) NOT NULL,AUTHOR VARCHAR(30) NOT NULL);


CREATE TABLE BOOK_ADOPTION(COURSE INTEGER NOT NULL,SEM INTEGER NOT NULL,BOOK_ISBN INTEGER NOT NULL,PRIMARY KEY(COURSE_,SEM,BOOK_ISBN),FOREIGN KEY (COURSE) REFERENCES COURSE(COURSE) ,FOREIGN KEY(BOOK_ISBN) REFERENCES TEXT(BOOKISBN));

INSERT INTO STUDENT VALUES('1BM02IS012','ANSHUMANATRI','DATBASE','15-JAN-84');INSERT INTO STUDENT VALUES('1BM02CS012','A MNC','DMS','25-FEB-84');INSERT INTO STUDENT VALUES('1BM02TC012','TELE TECHNO','SSDT','11-DEC-84');INSERT INTO STUDENT VALUES('1BM02EE012','ELCTRA','POWER GENERATION','1-APR-84');INSERT INTO STUDENT VALUES('1BM02EC012','GG','POWER ELECTRONICS','5-NOV-84');INSERT INTO COURSE VALUES(1,'DATABASE','IS');INSERT INTO COURSE VALUES(2,'DMS','IS');INSERT INTO COURSE VALUES(3,'SSDT','TC');INSERT INTO COURSE VALUES(4,'POWER GENERATION','EE');INSERT INTO COURSE VALUES(5,'POWER ELECTRONICS','EC');INSERT INTO TEXT VALUES(1,'DATABASE A SYSTEMATICAPPROACH','JOHN WILEY','R ASHOK KUMAR');INSERT INTO TEXT VALUES(2,'DMS FOR DUMMIES','PEARSON','MADHUPRIYA');INSERT INTO TEXT VALUES(3,'SSDT NO ONE CAN TEACHBETTER','PEARSON','GAURA');INSERT INTO TEXT VALUES(4,'POWER GENERATIONBIBLE','TMH','MEENA');INSERT INTO TEXT VALUES(5,'POWER OF POWER ELECTRONICS','OREILLY','GG THE GREAT');INSERT INTO ENROLL VALUES('1BM02IS012',1,5,98);INSERT INTO ENROLL VALUES('1BM02CS012',2,3,88);INSERT INTO ENROLL VALUES('1BM02TC012',3,5,88);INSERT INTO ENROLL VALUES('1BM02EE012',4,5,88);INSERT INTO ENROLL VALUES('1BM02EC012',5,5,88);
INSERT INTO BOOK_ADOPTION VALUES(1,5,1);INSERT INTO BOOK_ADOPTION VALUES(2,3,2);INSERT INTO BOOK_ADOPTION VALUES(3,5,3);INSERT INTO BOOK_ADOPTION VALUES(4,5,4);INSERT INTO BOOK_ADOPTION VALUES(5,5,5);










--1
select cname
from book_adoption natural join course
group by course_no
having count(book_isbn) > 1

--2
select c.dept
from course c
where course_no in
(select course_no from book_adoption where
book_isbn=(select book_isbn from text where publisher='mcgraw'));
--another answer

select dept
from course NATURAL JOIN book_adoption NATURAL JOIN book_isbn
where publisher = 'mcgraw';
